"""
Generate a synthetic financial decision validation dataset.

V0.2 introduces controlled case types:
    - CLEAR_APPROVE
    - CLEAR_REJECT
    - BORDERLINE
    - CONFLICTING

The dataset is deterministic and reproducible.
Reference decisions are generated by explicit rules, not by an LLM.

IMPORTANT:
    risk_score, risk_band, case_type and reference_decision are
    validation metadata. They should NOT be provided to the LLM.
"""

from pathlib import Path

import numpy as np
import pandas as pd


RANDOM_STATE = 42

CASE_COUNTS = {
    "CLEAR_APPROVE": 30,
    "CLEAR_REJECT": 30,
    "BORDERLINE": 20,
    "CONFLICTING": 20,
}


def calculate_risk_score(df: pd.DataFrame) -> pd.Series:
    """Calculate deterministic reference risk score."""

    score = np.zeros(len(df), dtype=int)

    # Debt burden
    score += np.where(df["debt_to_income"] > 0.45, 2, 0)
    score += np.where(
        (df["debt_to_income"] > 0.30)
        & (df["debt_to_income"] <= 0.45),
        1,
        0,
    )

    # Employment stability
    score += np.where(df["employment_years"] < 2, 1, 0)
    score += np.where(df["employment_years"] < 1, 1, 0)

    # Credit history
    score += np.where(df["credit_history_years"] < 3, 1, 0)
    score += np.where(df["credit_history_years"] < 1.5, 1, 0)

    # Previous defaults
    score += np.where(df["previous_defaults"] == 1, 3, 0)

    # Requested amount relative to annual income
    amount_to_income = (
        df["requested_amount"] / (df["income"] * 12)
    )

    score += np.where(amount_to_income > 2.5, 2, 0)
    score += np.where(
        (amount_to_income > 1.5)
        & (amount_to_income <= 2.5),
        1,
        0,
    )

    return pd.Series(score, index=df.index)


def assign_reference_decision(
    risk_score: pd.Series,
) -> pd.Series:
    """Map risk score to deterministic reference decision."""

    return pd.Series(
        np.where(
            risk_score <= 2,
            "APPROVE",
            "REJECT",
        ),
        index=risk_score.index,
    )


def assign_risk_band(
    risk_score: pd.Series,
) -> pd.Series:
    """Map risk score to a descriptive risk band."""

    return pd.Series(
        np.select(
            [
                risk_score <= 1,
                risk_score <= 3,
                risk_score <= 5,
            ],
            [
                "LOW",
                "MEDIUM",
                "HIGH",
            ],
            default="VERY_HIGH",
        ),
        index=risk_score.index,
    )


def generate_clear_approve(
    rng: np.random.Generator,
    n: int,
) -> pd.DataFrame:
    """Generate cases with predominantly positive signals."""

    return pd.DataFrame(
        {
            "income": rng.integers(5000, 14001, n),
            "debt_to_income": np.round(
                rng.uniform(0.10, 0.25, n), 3
            ),
            "employment_years": np.round(
                rng.uniform(5.0, 15.0, n), 1
            ),
            "credit_history_years": np.round(
                rng.uniform(5.0, 20.0, n), 1
            ),
            "previous_defaults": np.zeros(n, dtype=int),
            "requested_amount": rng.integers(
                2000, 20001, n
            ),
        }
    )


def generate_clear_reject(
    rng: np.random.Generator,
    n: int,
) -> pd.DataFrame:
    """Generate cases with predominantly negative signals."""

    return pd.DataFrame(
        {
            "income": rng.integers(1800, 7001, n),
            "debt_to_income": np.round(
                rng.uniform(0.46, 0.65, n), 3
            ),
            "employment_years": np.round(
                rng.uniform(0.2, 2.0, n), 1
            ),
            "credit_history_years": np.round(
                rng.uniform(0.5, 2.5, n), 1
            ),
            "previous_defaults": rng.choice(
                [0, 1],
                size=n,
                p=[0.25, 0.75],
            ),
            "requested_amount": rng.integers(
                25000, 60001, n
            ),
        }
    )


def generate_borderline(
    rng: np.random.Generator,
    n: int,
) -> pd.DataFrame:
    """Generate cases close to the reference decision boundary."""

    return pd.DataFrame(
        {
            "income": rng.integers(3000, 9001, n),
            "debt_to_income": np.round(
                rng.uniform(0.28, 0.46, n), 3
            ),
            "employment_years": np.round(
                rng.uniform(1.5, 5.0, n), 1
            ),
            "credit_history_years": np.round(
                rng.uniform(2.0, 5.0, n), 1
            ),
            "previous_defaults": rng.choice(
                [0, 1],
                size=n,
                p=[0.90, 0.10],
            ),
            "requested_amount": rng.integers(
                10000, 35001, n
            ),
        }
    )


def generate_conflicting(
    rng: np.random.Generator,
    n: int,
) -> pd.DataFrame:
    """
    Generate cases with deliberately conflicting signals.

    Examples:
        strong income + high debt
        long employment + previous default
        low debt + large requested amount
    """

    rows = []

    for _ in range(n):
        pattern = rng.integers(0, 3)

        if pattern == 0:
            # Strong positive income/employment
            # but high debt burden.
            row = {
                "income": int(rng.integers(8000, 14001)),
                "debt_to_income": round(
                    rng.uniform(0.48, 0.60), 3
                ),
                "employment_years": round(
                    rng.uniform(7.0, 15.0), 1
                ),
                "credit_history_years": round(
                    rng.uniform(7.0, 20.0), 1
                ),
                "previous_defaults": 0,
                "requested_amount": int(
                    rng.integers(10000, 30001)
                ),
            }

        elif pattern == 1:
            # Strong positive financial profile
            # but previous default.
            row = {
                "income": int(rng.integers(7000, 14001)),
                "debt_to_income": round(
                    rng.uniform(0.15, 0.30), 3
                ),
                "employment_years": round(
                    rng.uniform(7.0, 15.0), 1
                ),
                "credit_history_years": round(
                    rng.uniform(7.0, 20.0), 1
                ),
                "previous_defaults": 1,
                "requested_amount": int(
                    rng.integers(8000, 25001)
                ),
            }

        else:
            # Low debt and stable employment
            # but unusually large requested amount.
            row = {
                "income": int(rng.integers(5000, 10001)),
                "debt_to_income": round(
                    rng.uniform(0.15, 0.28), 3
                ),
                "employment_years": round(
                    rng.uniform(5.0, 12.0), 1
                ),
                "credit_history_years": round(
                    rng.uniform(5.0, 15.0), 1
                ),
                "previous_defaults": 0,
                "requested_amount": int(
                    rng.integers(35000, 60001)
                ),
            }

        rows.append(row)

    return pd.DataFrame(rows)


def generate_cases() -> pd.DataFrame:
    """Generate the complete controlled validation dataset."""

    rng = np.random.default_rng(RANDOM_STATE)

    generators = {
        "CLEAR_APPROVE": generate_clear_approve,
        "CLEAR_REJECT": generate_clear_reject,
        "BORDERLINE": generate_borderline,
        "CONFLICTING": generate_conflicting,
    }

    frames = []

    for case_type, count in CASE_COUNTS.items():
        frame = generators[case_type](rng, count)
        frame["case_type"] = case_type
        frames.append(frame)

    df = pd.concat(
        frames,
        ignore_index=True,
    )

    # Deterministic case IDs
    df.insert(
        0,
        "case_id",
        [
            f"CASE_{i:04d}"
            for i in range(1, len(df) + 1)
        ],
    )

    # Reference policy
    df["risk_score"] = calculate_risk_score(df)

    df["risk_band"] = assign_risk_band(
        df["risk_score"]
    )

    df["reference_decision"] = assign_reference_decision(
        df["risk_score"]
    )

    # Reproducible ordering
    df = df.sort_values(
        ["case_type", "case_id"]
    ).reset_index(drop=True)

    return df


def main() -> None:
    print("=" * 70)
    print("LLM FINANCIAL DECISION VALIDATION")
    print("SYNTHETIC DATA GENERATION V0.2")
    print("=" * 70)

    df = generate_cases()

    output_path = (
        Path(__file__).resolve().parent / "cases.csv"
    )

    df.to_csv(
        output_path,
        index=False,
    )

    print("\n[1] DATASET")
    print(f"Cases generated: {len(df)}")
    print(f"Columns:         {len(df.columns)}")
    print(f"Random state:    {RANDOM_STATE}")

    print("\n[2] CASE TYPE")
    print(
        df["case_type"]
        .value_counts()
        .sort_index()
        .to_string()
    )

    print("\n[3] REFERENCE DECISION")
    print(
        df["reference_decision"]
        .value_counts()
        .to_string()
    )

    print("\n[4] RISK BAND")
    print(
        df["risk_band"]
        .value_counts()
        .sort_index()
        .to_string()
    )

    print("\n[5] CASE TYPE × REFERENCE DECISION")
    print(
        pd.crosstab(
            df["case_type"],
            df["reference_decision"],
        ).to_string()
    )

    print("\n[6] CASE TYPE × RISK BAND")
    print(
        pd.crosstab(
            df["case_type"],
            df["risk_band"],
        ).to_string()
    )

    print("\n[7] DATA PREVIEW")
    print(
        df.head(12).to_string(index=False)
    )

    print("\n[8] OUTPUT")
    print(f"Saved to: {output_path}")

    print("\nGeneration completed successfully.")


if __name__ == "__main__":
    main()